[package]
name = "fuckin_service"
version = "0.1.0"
authors = ["Jason Birch <jbirch@jbirch.net>"]
edition = "2018"

[dependencies]
fuckin_lib = { path = "fuckin_lib", version = "~0" }
actix-web = "3.2.0"